### ISSUE TITLE
YCSB mysql test always show low throughput and connections are in sleep mode

### ISSUE THREAD

**Issue by syebay** [brianfrankcooper/YCSB#1036]
I am running YCSB benchmark testing against MySql database. With 1 thread, and 1000 batch size, 100% write/update, I am able to see 60ops/sec. That is way too low. 

I used workloada, here is the parameters:
recordcount=1000000
operationcount=1000000
workload=com.yahoo.ycsb.workloads.CoreWorkload
readallfields=true
readproportion=0
updateproportion=1
scanproportion=0
insertproportion=0
fieldcount=1
fieldlength=4000
#requestdistribution=zipfian
requestdistribution=latest

The command that I use is:
./bin/ycsb load jdbc -P workloads/workloada -p db.driver=com.mysql.jdbc.Driver -p db.url=xxx -p db.user=xxx -p db.passwd=xxx -s -threads 5 -p db.batchsize=1000 -p jdbc.fetchsize=1000 -p jdbc.autocommit=false -p jdbc.batchsize=1000

When I look at mysql process list in mysql database, I see that all connections are in sleep mode.  What could be wrong?

**Comment by allanbank** [comment]
The time for each operation is not just the time to process the query on the server. It includes the time to:

1. The YCSB client to prepare the select query.
2. The client to parse the select statement in the mysql driver,
3. The client to marshall the query to bytes and send the message to the server,
4. The message to transfer over the network from the client to the server
5. The server to decode and execute the query,
6. The server to marshal the result back to the client,
7. The results to transfer from the server to the client,
8. The client mysql driver to decode the response,
9. The YCSB client driver to process the results and return the status.

In my experience steps 4 and 7 (network latency) will take the lion share of the request time. The only way to combat that is to:

* move the client closer to the server and 
* create more client threads which will keep more requests in flight at one time. 

You will want to experiment with gradually increasing the number of threads to determine the optimal value.

**Comment by syebay** [comment]
Hi Allan,
Thanks for replying my question.  When I am monitoring the mysql process list, 99.9% of the time, YCSB mysql thread is in sleeping mode, that probably means that the client is busy preparing the data to load to the database.  This doesn't make sense to me, since the purpose of YCSB is to stress test the MySql database, I would expect the client is fast enough to stress the DB.

**Comment by allanbank** [comment]
Is the client running on the same machine as the MySQL server? If not what is the ping time between the two machines?

**Comment by syebay** [comment]
The client machine is not running on the same machine as MySQL server. The ping time between two machines is about 15ms.

**Comment by allanbank** [comment]
I think there may be a couple things going on here.

First the 15ms ping time means that the maximum operation rate that you can possibly see is ~67 (1000ms/15ms) operations/thread. You are using 5 threads to that gives a upper bound of 355. There is some overhead in MySQL and the client but those should be much smaller than the network latency. If we assume 1 ms on each side (17ms total) we are down to 295 operations per second.

Since you are only seeing 60 ops/sec there is something else still going on.

I also noticed that you have specified to use batching (db.batchsize=1000) but you have not turned on batching via the JDBC Batch API (jdbc.batchupdateapi). I think that means that the 1000 insert statement are being sent to the MySQL server one at a time to be added to a single batch transaction. There is then another round trip to the MySQL server to commit the transaction. I think that adds to the lack of load on the server. 

Can you try turning on "-p jdbc.batchupdateapi=true" and see if that improves the performance? I would also be interested to see what the performance is without batching...

**Comment by busbey** [comment]
closing as stale. if you're still facing issues please reopen and address the questions above.
