### ISSUE TITLE
Benchmark with new MongoDB Async Driver

### ISSUE THREAD

**Issue by sgzhang** [brianfrankcooper/YCSB#1039]
Hi,
I am try to use benchmark [mongodb-async-driver](http://mongodb.github.io/mongo-java-driver/3.5/driver-async/) from the official site by implementing DB layer by myself. However, I do not know how to do it correctly, since all function in async driver use callback style. 

In my implementation, for example, I always use this way (https://pastebin.com/wBAv4dhu) to override read function. The result shows both async-driver and sync-driver performs almost the same (I varies `maxPoolSize` and `threadCount`). Does anyone can give me a concrete example of how to efficiently use async-driver for mongodb? 

Thanks.

**Comment by allanbank** [comment]
The two MongoDB Inc. drivers I would expect to perform very similar with a slight advantage to the non-async driver since the core connection handling logic is the same. (e.g., One request per connection at a time.[1])

What you have is a perfectly reasonable way of converting the asynchronous interface into a synchronous one. You may want to also look at the java.util.concurrent.CompletableFuture class. That can simplify the code a little bit to something like:

    final CompletableFuture<Document> future = new CompletableFuture<>();
    findIterable.first(new SingleResultCallback<Document>() {
        @Override
        public void onResult(Document result, Throwable throwable) {
          if( throwable != null ) {
            future.completeExceptionally(throwable);
          } else {
            future.complete(result);
          }
        }
    });
    Document found = future.get();
    fillMap( found, result);
    return  found != null ? Status.OK : Status.NOT_FOUND;

With Java 8 Lambda we can clean that up a little more with:

    final CompletableFuture<Document> future = new CompletableFuture<>();
    findIterable.first((result, throwable) -> {
        if( throwable != null ) {
          future.completeExceptionally(throwable);
        } else {
          future.complete(result);
        }
    });
    Document found = future.get();
    fillMap( found, result);
    return  found != null ? Status.OK : Status.NOT_FOUND;

HTH,
Rob.

1: I have not looked at the async driver from MongoDB Inc. for over a year now so that may not still be the case. I tried to validate that is still the case but the code is tricky to follow but it appears to still be the case.

**Comment by sgzhang** [comment]
Thanks @allanbank 

I am also interested in the (mongodb-async-driver)[http://www.allanbank.com/mongodb-async-driver/index.html] which is already included in YCSB mongodb-binding repo. I have done some experiments and got similar results as the website http://www.allanbank.com/mongodb-async-driver/performance/ycsb.html shows. The following figure shows one of interesting results I got.
![](https://i.imgur.com/khSH4Ns.png)
I run the experiments with two dedicated VMs for YCSB client and MongoDB respectively, each VM has quad-core settings.

I am not sure if you can see it clearly, in the figure, the arrows shows mongodb-async-driver performs the best when the connection pool is set to 4. Here, I have several questions:
1. I assume 4 connections can efficiently utilize the quad-core, is it right?
2. I have read mongodb-async-driver source code and corresponding YSCB DB layer, from client perspective, it still follows the rule: send a request and waits for response. In my opinion, this is NOT asynchronous at all, but how does mongodb-async-driver outperform another mongodb-driver almost in all scenarios, could you give me some hints?

**Comment by allanbank** [comment]
> 1. I assume 4 connections can efficiently utilize the quad-core, is it right?

This is a bit of a loaded question. It depends on what you mean by efficient and utilize. I suspect you will find that for both drivers the client machine is not near 100% CPU utilization. The clients will be sending most of its time waiting for replies.

The maximum scaling for the client should be more dependant on the server side resources than the client.

> 2. I have read mongodb-async-driver source code and corresponding YSCB DB layer, from client perspective, it still follows the rule: send a request and waits for response. In my opinion, this is NOT asynchronous at all, but how does mongodb-async-driver outperform another mongodb-driver almost in all scenarios, could you give me some hints?

The mongodb-async-driver multiplexes multiple requests on a single connection. That's it. It is not magic. By multiplexing the requests on fewer connections you use fewer resources on the server (and client) and also get some small latency improvements on the server since there is less threads bouncing (we keep the thread for the connection busy.   

The MongoDB Inc. driver grabs an open connection from the pool, sends the request, receives the response and then returns the connection to the free pool. You have to scale the connection count in order to get more throughput. 

The mongodb-async-driver instead will send multiple requests down a single connection and tracks the response back. The performance you are seeing is the result of the YCSB client not having to wait for a connection to become free with the mongodb-async-driver. The multiplexing is done using asynchronous techniques in the core of the driver. Putting a synchronous facade on an asynchronous implementation is fairly easy and the driver does that for developer ease of use. The core is still asynchronous and the multiplexing is a natural extension.

**Comment by sgzhang** [comment]
Thanks for your patience, it helps me understand the code better.

**Comment by allanbank** [comment]
Not a problem. 

If you don't have any additional questions would you mind closing this ticket? Feel free to open another ticket in the future if additional questions come up.

Rob.
