### ISSUE TITLE
Running Workload D and E in Parallel

### ISSUE THREAD

**Issue by ntrhieu89** [brianfrankcooper/YCSB#1061]
Hi,

I am trying to run workloads D and E in parallel (using multiple nodes to issue actions).
The problem is the `insert` operation. How to prevent two different nodes to insert the same new user to the data store?

This link https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload-in-Parallel gives an instruction for loading the data store with multiple nodes but doesn't mention anything about the run phase.

Thanks,
Hieu Nguyen

**Comment by busbey** [comment]
the `insertstart` and `insertcount` properties are used to constrain the keys chosen for all operations, including when workloads are in the run phase.

**Comment by busbey** [comment]
closing as stale. if you're still having trouble please reopen.

**Comment by perdelt** [comment]
Hi, I still have this problem. I load data with
```
recordcount=1000000
operationcount=500000
workload=site.ycsb.workloads.CoreWorkload

readallfields=true

readproportion=0
updateproportion=0
scanproportion=0.95
insertproportion=0.05

requestdistribution=zipfian

maxscanlength=100

scanlengthdistribution=uniform

insertstart=0
insertcount=500000
```
and
```
recordcount=1000000
operationcount=500000
workload=site.ycsb.workloads.CoreWorkload

readallfields=true

readproportion=0
updateproportion=0
scanproportion=0.95
insertproportion=0.05

requestdistribution=zipfian

maxscanlength=100

scanlengthdistribution=uniform

insertstart=500000
insertcount=500000
```
without a problem. I then have two processes for workload E
First
```
recordcount=2000000
operationcount=500000
workload=site.ycsb.workloads.CoreWorkload

readallfields=true

readproportion=0
updateproportion=0
scanproportion=0.95
insertproportion=0.05

requestdistribution=zipfian

maxscanlength=100

scanlengthdistribution=uniform

insertstart=1000000
insertcount=500000
```
Second
```
recordcount=2000000
operationcount=500000
workload=site.ycsb.workloads.CoreWorkload

readallfields=true

readproportion=0
updateproportion=0
scanproportion=0.95
insertproportion=0.05

requestdistribution=zipfian

maxscanlength=100

scanlengthdistribution=uniform

insertstart=1500000
insertcount=500000
```
and I receive a lot of PK violation errors.
Can you help me, where am I doing something wrong?
Many thanks!

**Comment by seybi87** [comment]
Hi @perdelt 

the problems with the PV violations are caused by the specified `recordcount` values in the parallel RUN phase.  The `recordcount` also specifies the key range of the inserted records, i.e. in the RUN phase you have specified for both workloads  `recordcount=2000000`.

In consequence, the Workloads E1 and E2 will insert records from the key range `insertstart` to `recordcount`:
*  Workload E-1  `1000000 to 2000000` 
*  Workload E-2  `1500000 to 2000000`

Setting the `recordcount=1500000` for Workload E-1 should solve the issue.

**Comment by Lsacy** [comment]
Dear @seybi87 ,

I found out recordcount is actually the only parameter that matters during a run process. YCSB starts reading/scanning backward from recordcount position, and tries to insert from this position.

By using the same setting as @perdelt has provided with the adjusted recordcount setting, the insert problem got solved but now there is read failure, since there are actually no records between 1000000 and 1500000.

The only way to mitigate this is by leaving some space between the two load operations and insert new records inbetween the space.

For example, during parallel load process
for load 1: 
insertstart = 0
insertcount = 50000
recordcount = 150000

for load 2:
insertstart = 100000
insertcount = 50000
recordcount = 150000

After loading there will be empty key spaces between 50000 - 100000


Now for parallel run process, only recordcount plays a role, insert start will absolutely have no effect
setting run 1:
recordcount = 50000

setting run 2:
recordcount = 150000

will cause neither insert error nor read failure, only if requestdistribution=zipfian. When requestdistribution=latest, then there still will be read failure.

I was wondering if this was intended or did I discover something unintentional?
