### ISSUE TITLE
Still waiting for thread Thread-2 to complete. Workload status: true

### ISSUE THREAD

**Issue by 2victoria** [brianfrankcooper/YCSB#1067]
when i use ycsb to test cassandra,i meet the problems:still waiting for thread Thread-2 to complete. Workload status: true.
Stop requested for workload. Now Joining!
Still waiting for thread Thread-2 to complete. Workload status: true
[OVERALL], RunTime(ms), 62296.0
[OVERALL], Throughput(ops/sec), 2291.639912674971
[TOTAL_GCS_PS_Scavenge], Count, 6.0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 279.0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.44786182098369076
[TOTAL_GCS_PS_MarkSweep], Count, 0.0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0.0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 6.0
[TOTAL_GC_TIME], Time(ms), 279.0
[TOTAL_GC_TIME_%], Time(%), 0.44786182098369076
[READ], Operations, 71597.0
[READ], AverageLatency(us), 430.5996200958141
[READ], MinLatency(us), 278.0
[READ], MaxLatency(us), 170239.0
[READ], 95thPercentileLatency(us), 610.0
[READ], 99thPercentileLatency(us), 1012.0
[READ], Return=OK, 71597
[CLEANUP], Operations, 1.0
[CLEANUP], AverageLatency(us), 2294784.0
[CLEANUP], MinLatency(us), 2293760.0
[CLEANUP], MaxLatency(us), 2295807.0
[CLEANUP], 95thPercentileLatency(us), 2295807.0
[CLEANUP], 99thPercentileLatency(us), 2295807.0
[UPDATE], Operations, 71163.0
[UPDATE], AverageLatency(us), 383.21522420358895
[UPDATE], MinLatency(us), 247.0
[UPDATE], MaxLatency(us), 52479.0
[UPDATE], 95thPercentileLatency(us), 527.0
[UPDATE], 99thPercentileLatency(us), 822.0
[UPDATE], Return=OK, 71163
who can help me solve the problem?

**Comment by tomer-sandler** [comment]
Hitting the same issue when running YCSB on Google bigtable.

**Setup**
Bigtable 20 nodes
4 Loader VMs on GCE: n1-standard-8 (8 vCPU 30 GB RAM)
Each loader VM is running 2 YCSB instances (total 8)
Dataset = 1B records = ~1.25TB
I was running with 100 threads per YCSB instance,  went down to 80 -> 60 -> 40 -> 30 and it still happens on workloadb + workloadc + workloadd

Since I'm running multiple YCSB, each instance is working on it's on range.

**Commands used**

**Loader-1**
nohup sudo ~/YCSB/bin/ycsb run googlebigtable -p columnfamily=cf -p google.bigtable.project.id=skilled-adapter-452 -p google.bigtable.instance.id=tomer-instance -p google.bigtable.auth.json.keyfile=/home/`whoami`/YCSB/Scylla-2917fb63f00d.json -p recordcount=1000000000 -p operationcount=125000000 -p insertstart=0 -p insertcount=125000000 -p maxexecutiontime=1800 -s -P workloads/workloadb -threads 30 > 1bigtable_1TB_workloadb &

nohup sudo ~/YCSB/bin/ycsb run googlebigtable -p columnfamily=cf -p google.bigtable.project.id=skilled-adapter-452 -p google.bigtable.instance.id=tomer-instance -p google.bigtable.auth.json.keyfile=/home/`whoami`/YCSB/Scylla-2917fb63f00d.json -p recordcount=1000000000 -p operationcount=125000000 -p insertstart=125000000 -p insertcount=125000000 -p maxexecutiontime=1800 -s -P workloads/workloadb -threads 30 > 2bigtable_1TB_workloadb &

**Loader-2**
nohup sudo ~/YCSB/bin/ycsb run googlebigtable -p columnfamily=cf -p google.bigtable.project.id=skilled-adapter-452 -p google.bigtable.instance.id=tomer-instance -p google.bigtable.auth.json.keyfile=/home/`whoami`/YCSB/Scylla-2917fb63f00d.json -p recordcount=1000000000 -p operationcount=125000000 -p insertstart=250000000 -p insertcount=125000000 -p maxexecutiontime=1800 -s -P workloads/workloadb -threads 30 > 1bigtable_1TB_workloadb &

nohup sudo ~/YCSB/bin/ycsb run googlebigtable -p columnfamily=cf -p google.bigtable.project.id=skilled-adapter-452 -p google.bigtable.instance.id=tomer-instance -p google.bigtable.auth.json.keyfile=/home/`whoami`/YCSB/Scylla-2917fb63f00d.json -p recordcount=1000000000 -p operationcount=125000000 -p insertstart=375000000 -p insertcount=125000000 -p maxexecutiontime=1800 -s -P workloads/workloadb -threads 30 > 2bigtable_1TB_workloadb &

**Loader-3**
nohup sudo ~/YCSB/bin/ycsb run googlebigtable -p columnfamily=cf -p google.bigtable.project.id=skilled-adapter-452 -p google.bigtable.instance.id=tomer-instance -p google.bigtable.auth.json.keyfile=/home/`whoami`/YCSB/Scylla-2917fb63f00d.json -p recordcount=1000000000 -p operationcount=125000000 -p insertstart=500000000 -p insertcount=125000000 -p maxexecutiontime=1800 -s -P workloads/workloadb -threads 30 > 1bigtable_1TB_workloadb &

nohup sudo ~/YCSB/bin/ycsb run googlebigtable -p columnfamily=cf -p google.bigtable.project.id=skilled-adapter-452 -p google.bigtable.instance.id=tomer-instance -p google.bigtable.auth.json.keyfile=/home/`whoami`/YCSB/Scylla-2917fb63f00d.json -p recordcount=1000000000 -p operationcount=125000000 -p insertstart=625000000 -p insertcount=125000000 -p maxexecutiontime=1800 -s -P workloads/workloadb -threads 30 > 2bigtable_1TB_workloadb &

**Loader-4**
nohup sudo ~/YCSB/bin/ycsb run googlebigtable -p columnfamily=cf -p google.bigtable.project.id=skilled-adapter-452 -p google.bigtable.instance.id=tomer-instance -p google.bigtable.auth.json.keyfile=/home/`whoami`/YCSB/Scylla-2917fb63f00d.json -p recordcount=1000000000 -p operationcount=125000000 -p insertstart=750000000 -p insertcount=125000000 -p maxexecutiontime=1800 -s -P workloads/workloadb -threads 30 > 1bigtable_1TB_workloadb &

nohup sudo ~/YCSB/bin/ycsb run googlebigtable -p columnfamily=cf -p google.bigtable.project.id=skilled-adapter-452 -p google.bigtable.instance.id=tomer-instance -p google.bigtable.auth.json.keyfile=/home/`whoami`/YCSB/Scylla-2917fb63f00d.json -p recordcount=1000000000 -p operationcount=125000000 -p insertstart=875000000 -p insertcount=125000000 -p maxexecutiontime=1800 -s -P workloads/workloadb -threads 30 > 2bigtable_1TB_workloadb &

**Comment by busbey** [comment]
what version of YCSB?

**Comment by tomer-sandler** [comment]
This one: https://github.com/robertpang/YCSB/tree/i458/cassandra

**Comment by busbey** [comment]
Can you reproduce the problem with YCSB's current master or a released version?

**Comment by tomer-sandler** [comment]
Next time I'll be using YCSB on Cloud Bigtable, I'll use one of the 2 you suggest and see if it reproduce.
In the one I used, it reproduced ALL the time.

**Comment by busbey** [comment]
Thanks @tomer-sandler!

How about you @2victoria? Could you get me a YCSB version #?

**Comment by tomer-sandler** [comment]
@busbey I downloaded the latest ycsb-0.12.0 and tried to run the load on Google Cloud Bigtable.
I can't run it at all due to https://github.com/brianfrankcooper/YCSB/issues/1048. I'm hitting the 
```java.lang.IllegalStateException: Neither Jetty ALPN nor OpenSSL via netty-tcnative were properly configured.```
Note that with this: https://github.com/robertpang/YCSB/tree/i458/cassandra version I did not have that problem.

Also, YCSB docs need to be updated as there are 2 new mandatory -p that must be supplied in order to run (which were not needed in robertpang fork I've been using):
```
-p google.bigtable.cluster.name=[cluster_name]
-p google.bigtable.zone.name=[cluster_zone]
```

**Comment by busbey** [comment]
could you try again now with the 0.14.0 release @tomer-sandler ?

**Comment by busbey** [comment]
closing as stale. if someone can reproduce using the 0.14.0 release or newer, please reopen.

**Comment by ZuluPro** [comment]
@busbey I can reproduce this with postgrenosql on 0.17.0.

**Comment by amgads** [comment]
@busbey i can re-produce with mysql/mariadb -- please see issue #1622
