### ISSUE TITLE
inconsistent load on Mongodb cluster

### ISSUE THREAD

**Issue by annisaMS** [brianfrankcooper/YCSB#1093]
I have 2 type of sharded cluster :
1. sharded cluster that consist of 3 single mongod instance
2. sharded cluster that consist of 3 replica set
 When I benchmarked using YCSB, sharded cluster that consist of 3 single mongod instance didn't show better performance when adding more shard. The test result was unstable, why it can happen?

**Comment by allanbank** [comment]
Can you post your results and test hardware and configuration?

What do you mean by unstable?

Rob.

**Comment by annisaMS** [comment]
I use dynamic private ip, I just use default configuration of YCSB,
for workload a, the test result is

**Comment by annisaMS** [comment]
if I add more shard, the runtime isn't increase
for ip, I use dynamic private ip, and I just use default configuration of YCSB,
for workload a, the test result is
![image](https://user-images.githubusercontent.com/22288935/36065198-46e95d4c-0e4c-11e8-9f3f-898fcccb5130.png)
![image](https://user-images.githubusercontent.com/22288935/36065203-55920d76-0e4c-11e8-96c1-aff255806955.png)

and my hardware spec is
![image](https://user-images.githubusercontent.com/22288935/36065212-8d673d8e-0e4c-11e8-8c30-dce1e0181302.png)


Now I'm trying to use static ip for my cluster, hope it can work

**Comment by allanbank** [comment]
How is the size (500MB, 1GB, etc) computed?

**Comment by annisaMS** [comment]
500000,1000000,1500000,2000000 for recordcount and operationcount

**Comment by allanbank** [comment]
Can you plot the data byt read/update operation latency percentiles instead of total run time?

What was the process you followed to reset the cluster's state between runs, if any? What was the order of the runs? (I'm assuming you did the split and balance between shard levels...)

Was anything else running on the machine during the tests?

**Comment by annisaMS** [comment]
![image](https://user-images.githubusercontent.com/22288935/36065454-0a86c868-0e50-11e8-931e-a9ba569de0b9.png)
![image](https://user-images.githubusercontent.com/22288935/36065462-1523753c-0e50-11e8-8044-d525e60a10a7.png)
after load and run phase, I drop YCSB db , and recreate it, then I just enable the db for all shards
I think there's no other running process except YCSB benchmarking

**Comment by allanbank** [comment]
> after load and run phase, I drop YCSB db , and recreate it, then I just enable the db for all shards
I think there's no other running process except YCSB benchmarking

So you are not re-splitting the collection and ensuring it is balanced before each test run? Dropping the database removes all of the chunks so you are back to all of the data on one shard.

**Comment by annisaMS** [comment]
db.usertable.ensureIndex({"_id":"hashed"})
sh.shardCollection("ycsb.usertable",{"_id":"hashed"})
is that splitting?

**Comment by allanbank** [comment]
You may get the splitting if you don't create the index first. 

sh.shardCollection(...) will split and balance the collection if it does not already exist. The ensureIndex will create the collection so the sh.shardCollection(...) won't split and balance. 

I say "may" because any left over pieces of the collection can stop the sh.shardCollection(...) from doing the split and balance. There is likely to be pieces left in the config database that will also stop it from working.

You can tell if the collection is split and balanced via the sh.status() command. It should show the same number of chunks on each shard.

The best thing is to use the split script I provided from your other ticket and then don't drop the collection, just do a db.usertable.remove({}) between runs (if needed). You can also do a compact on the collection after the remove to further get back to a know starting state.

**Comment by annisaMS** [comment]
ok, thanks ..

**Comment by morcelicaio** [comment]
Hi, @annisaMS , Are you using mongodb atlas to work with cluster?
