### ISSUE TITLE
Documentation issue: Can't run workloadd and workloade for a variety of throughputs

### ISSUE THREAD

**Issue by lovengulu** [brianfrankcooper/YCSB#1178]
#### Description:
According to  [https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads](https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads) I tried to run workloadd few times without re-loading the database between test. The first test runs ok. The 2nd fails with errors like the following:
com.mongodb.MongoWriteException: E11000 duplicate key error collection: ycsb.usertable index: _id_ dup key: { : "user3339209904021769693" }
The exact issue is with workloade. 
Not sure if this is a bug or the above wiki page is wrong or I'm doing something wrong. The wiki page say:

> 6. Run workload D (using workloads/workloadd and “-t”) for a variety of throughputs. This workload inserts records, increasing the size of the database.  

I'm unable to run a test for "variety of throughputs". 

#### Exact steps I did:

#- load:
`/home/yuval/MongoDB-Benchmark/ycsb-0.14.0/bin/ycsb load mongodb -s -P /home/yuval/MongoDB-Benchmark/ycsb-0.14.0/workloads/workloadd -threads 10`

#- run first time on the DB:
`/home/yuval/MongoDB-Benchmark/ycsb-0.14.0/bin/ycsb run mongodb -s -P /home/yuval/MongoDB-Benchmark/ycsb-0.14.0/workloads/workloadd -threads 1
`#- The first time completes without errors

#- run the same once again:
`/home/yuval/MongoDB-Benchmark/ycsb-0.14.0/bin/ycsb run mongodb -s -P /home/yuval/MongoDB-Benchmark/ycsb-0.14.0/workloads/workloadd -threads 1`
#- on the 2nd time, I'm getting "E11000 duplicate key error".
#-  The results of the 2nd time say (copied just the relevant lines):
> [INSERT], Operations, 5
> [INSERT], Return=OK, 5
> [INSERT], Return=ERROR, 47
> [INSERT-FAILED], Operations, 47

**Comment by adally** [comment]
Did you delete the table data before load?

**Comment by busbey** [comment]
the issue is that the generator for keys has to know how many records already exist to avoid making a duplicate. That means after each run you'll have to increase the record count via e.g. `-p recordcount=1050` (for a start of 1,000 records and a previous Workload D with 1,000 operations).

you could set `mongodb.upsert` which would switch from an insert to upsert to work around the issue if you don't want to have to reset the mongo table or update the record count so long as you don't mind measuring updates instead of pure inserts.

**Comment by busbey** [comment]
Closing as stale. If the suggested fix doesn't work feel free to reopen.
