### ISSUE TITLE
Retries during run phase

### ISSUE THREAD

**Issue by danielfireman** [brianfrankcooper/YCSB#1262]
Hi folks, good afternoon!

I noticed the insert operation has already the notion of retries configured by [core_workload_insertion_retry_limit](https://github.com/brianfrankcooper/YCSB/blob/e5f436cfb3dded3e63fb2ca71168d728b3d8a24f/core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java#L325) and [core_workload_insertion_retry_interval](https://github.com/brianfrankcooper/YCSB/blob/e5f436cfb3dded3e63fb2ca71168d728b3d8a24f/core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java#L325) properties.

What do you guys think about having this for the run phase? I am needing this on an experiment and I am keen to send the PRs if you guys think it is good. My first idea is to [make the current retry logic](https://github.com/brianfrankcooper/YCSB/blob/e5f436cfb3dded3e63fb2ca71168d728b3d8a24f/core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java#L599-L624) reusable and use it in the other operations.

Furthermore, would you prefer one knob or 5 pairs of knobs (one for each [operation](https://github.com/brianfrankcooper/YCSB/blob/e5f436cfb3dded3e63fb2ca71168d728b3d8a24f/core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java#L643-L656))?

**Comment by risdenk** [comment]
@danielfireman - I don't know if it makes sense to retry during the run phase. We would have to be careful about retrying inserts and updates (and what to do in that situation). During the insert phase I think it is ok since that isn't being measured? (I could be wrong here). I'm not against it being exposed as an option as long as the default stays the same as it is today (don't want someone to get different results because of retries on by default).

**Comment by danielfireman** [comment]
Good morning, @risdenk ! Sorry for the delay to answer.

I understand your points and agree with the risk of retrying inserts and updates. That said, I am going to close this issue and re-open (or create another one) after putting more thought and, if remains the case, describing more carefully the proposal.
