### ISSUE TITLE
The impact of the recordcount parameter

### ISSUE THREAD

**Issue by ssizmaster** [brianfrankcooper/YCSB#1272]
I would test the performance of operations count in HBase by using YCSB framework in an HBase table with 4000000 rows. Is there any difference between the two following commands (with or without the recordcount parameter) 

`bin/ycsb run hbase12 -P workloads/workloada  -p columnfamily=cf4 -p table=usertable4M -p zeropadding=8 -p insertorder=ordered  -p operationcount=5000 -p recordcount=4000000 > res1.txt
`

`bin/ycsb run hbase12 -P workloads/workloada  -p columnfamily=cf4 -p table=usertable4M -p zeropadding=8 -p insertorder=ordered  -p operationcount=5000 > res1.txt
`

Appreciate your help on this
Thanks,

**Comment by allanbank** [comment]
If you do not provide a record count on the command line then it uses the value in the workloads/workloada file (which is 1000) by default. The record count determines the set of records that the test expected to find already in the store. 

If the recordcount is larger for the 'run' than the value used in the 'load' phase then you will likely have operations fail in the 'run' phase due to records missing.

If the recordcount is smaller for the 'run' than the value used in the 'load' phase then you should not have read operations fail but some inserts may fail for duplicate records. You will also only run read operations on a smaller subset of the records than would/should/could have been used.

**Comment by ssizmaster** [comment]
Thank you @allanbank
