### ISSUE TITLE
Split Strategy for YCSB Benchmark

### ISSUE THREAD

**Issue by ssizmaster** [brianfrankcooper/YCSB#1273]
I would like to use the YCSB framework to test the HBase performance in parallel with 2 nodes and I found the flowing command in HBase official websites (https://issues.apache.org/jira/browse/HBASE-4163)

`bin/hbase org.apache.hadoop.hbase.util.RegionSplitter TABLE -c 200 -f FAMILY -D split.algorithm=YcsbSplit
`

Please what is the role of this command? is it necessary in parallel environment?
Thanks,

**Comment by allanbank** [comment]
Necessary - Probably not.  It should still "work" just the performance will not be optimal.

The presplit is to break up the key space into chunks across the cluster before the insert of data. This spreads the processing across the cluster from the start. 

Stores like HBase have mechanisms to dynamically create chunks in the key space over time. The problem is that tools like YCSB load a lot of data very quickly and then almost immediately drop it again. That does not give the dynamic mechanisms a chance to detect, split and move the data around to optimize performance. The presplit fixes that by breaking up the key space and assigning those to different nodes in the cluster and then loading the data straight into all of the nodes from the start. Without the presplit all of the data will likely (initially) land on a single node in the cluster.

**Comment by ssizmaster** [comment]
Thank you for response;

The parameter "-c 200" it should be equal to number of nodes in the cluster?

**Comment by allanbank** [comment]
I am not a HBase expert but ...

I would generally suggest setting it to some multiple of the number of nodes. Maybe 10x or 20x. That will ensure that any imbalance in the cluster (does N splits creates N or N+1 chunks?) is minimized.

**Comment by busbey** [comment]
That utility is from the HBase project, so we can't offer much help here.

As a contributor to both projects, I can say that particular HBase utility is not well maintained. I'd recommend you follow the table presplitting advice we offer in the README for the HBase client support here in YCSB:

https://github.com/brianfrankcooper/YCSB/blob/0.15.0/hbase098/README.md#3-create-a-hbase-table-for-testing

**Comment by ssizmaster** [comment]
Thank you
