### ISSUE TITLE
Using HBase APIs to access Cloud BigTable runs out of budget during initialization using service defaults and a large number of concurrent YCSB client threads.

### ISSUE THREAD

**Issue by liujiongxin** [brianfrankcooper/YCSB#1357]
In HBaseClient10.java, connection is static, meaning that all the threads will share the same connection. However, currentTable is not. This potentially add overhead to the server, as each thread will trigger "getTable" call seperately, even though the returned table object is the same.

Is it possible to make it shared across threads?

**Comment by busbey** [comment]
In HBase's 1.0+ APIs the `Table` object is supposed to be light weight and thus localized rather then shared like the heavy `Connection`. Why do you think it's adding a significant amount of overhead?

**Comment by liujiongxin** [comment]
getTable is a admin request rather than a data request (i.e., much fewer replicas), so admin server may be too hot under certain testing workload.

**Comment by busbey** [comment]
Please provide specific benchmark results with some analysis that this is a practical problem rather than a theoretical one.

**Comment by liujiongxin** [comment]
Ok, we have 10 GCE VMs, and each VM has 20 threads, so we hit the following error both at the run (read/update) stage:

"Not enough budget to allocate 1 for key `projects/xxx/instances/yyy/tables/ycsbloadv2:google.bigtable.admin.v2.BigtableTableAdmin.BigtableTableAdmin.GetTable`: has 100, limit 100"

The user side error is resource_exceeded (not retry-able), and the particular read/update fails.

**Comment by busbey** [comment]
This sounds like a limitation of the Cloud BigTable implementation of the HBase API more than an issue with our use of the HBase API. Especially given that the limitation appears to span clients that have no way to know about each other.

For reference, [the JavaDocs fro HBase on Connection](http://hbase.apache.org/1.2/apidocs/org/apache/hadoop/hbase/client/Connection.html) specifically call out that `Table` is not threadsafe and not recommended for pooling:

> Connection implementations are thread-safe, so that the client can create a connection once, and share it with different threads. Table and Admin instances, on the other hand, are light-weight and are not thread-safe. Typically, a single connection per client application is instantiated and every thread will obtain its own Table instance. Caching or pooling of Table and Admin is not recommended.

I'd expect the budget for GetTable is configurable and you can increase it to 200+ if you want to test 10 clients each running 20 threads. As an alternative, you could consider [using the YCSB binding for Cloud BigTable](https://github.com/brianfrankcooper/YCSB/blob/0.16.0/googlebigtable/README.md) directly rather than the HBase API facade for it.

**Comment by liujiongxin** [comment]
Thanks for the clarification. I will try to update the cloud bigtable binding in the future.

**Comment by busbey** [comment]
Please let us know if that doesn't work.
