### ISSUE TITLE
Can't run a workload with specified 'recordcount'

### ISSUE THREAD

**Issue by andrehgdias** [brianfrankcooper/YCSB#1457]
I can't run a workload with specified 'recordcount', even though I did load that same amount. It's always doing 1k operations instead of what I specified.
I tried command line parameter and external .dat file, both didn't work.

**Running on Ubuntu 18.04(Docker Container) with:**
- YCSB 0.17.0
- Python 2.7
- Java JDK 11
- Maven 3.6.0

**Command:**
`
./bin/ycsb run mongodb-async -P workloads/workloada -p recordcount=100000 -p mongodb.url=mongodb://172.18.0.3:27017/ycsb?w=1 -s > 'logs/running-workloadA.txt'
`

**Output:**
java -cp /ycsb-0.17.0/mongodb-binding/conf:/ycsb-0.17.0/conf:/ycsb-0.17.0/lib/core-0.17.0.jar:/ycsb-0.17.0/lib/jackson-mapper-asl-1.9.4.jar:/ycsb-0.17.0/lib/HdrHistogram-2.1.4.jar:/ycsb-0.17.0/lib/jackson-core-asl-1.9.4.jar:/ycsb-0.17.0/lib/htrace-core4-4.1.0-incubating.jar:/ycsb-0.17.0/mongodb-binding/lib/snappy-java-1.1.7.1.jar:/ycsb-0.17.0/mongodb-binding/lib/mongo-java-driver-3.8.0.jar:/ycsb-0.17.0/mongodb-binding/lib/slf4j-api-1.7.25.jar:/ycsb-0.17.0/mongodb-binding/lib/mongodb-async-driver-2.0.1.jar:/ycsb-0.17.0/mongodb-binding/lib/logback-core-1.1.2.jar:/ycsb-0.17.0/mongodb-binding/lib/logback-classic-1.1.2.jar:/ycsb-0.17.0/mongodb-binding/lib/mongodb-binding-0.17.0.jar site.ycsb.Client -db site.ycsb.db.AsyncMongoDbClient -P workloads/workloada -p recordcount=100000 -p mongodb.url=mongodb://172.18.0.3:27017/ycsb?w=1 -s -t
Command line: -db site.ycsb.db.AsyncMongoDbClient -P workloads/workloada -p recordcount=100000 -p mongodb.url=mongodb://172.18.0.3:27017/ycsb?w=1 -s -t
YCSB Client 0.17.0

Loading workload...
Starting test.
2020-09-23 14:33:43:338 0 sec: 0 operations; est completion in 0 second
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
2020-09-23 14:33:47:697 4 sec: 1000 operations; 229.36 current ops/sec; [READ: Count=510, Max=908287, Min=220, Avg=4412.97, 90=4811, 99=10151, 99.9=80511, 99.99=908287] [CLEANUP: Count=1, Max=4727, Min=4724, Avg=4726, 90=4727, 99=4727, 99.9=4727, 99.99=4727] [UPDATE: Count=490, Max=57855, Min=428, Avg=3259.5, 90=6007, 99=11623, 99.9=57855, 99.99=57855]

**Comment by busbey** [comment]
the `recordcount` property only changes how many keys YCSB believes should be present

* it determines how many keys we insert during a `ycsb load`
* it determines what range of keys we will pick from when doing operations in `ycsb run`

In order to change how many operations are performed in a `ycsb run` invocation you have to set the property `operationcount` to the desired number. Like `recordcount` it has a default of 1000.

I just realized [our wiki page on core workload properties](https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties) does not cover setting the operation count, so I'll go edit that to add it.

**Comment by andrehgdias** [comment]
Hey that worked, can close this now, thanks a lot!

**Comment by busbey** [comment]
I also updated the core properties wiki page to include operation count.

Thanks for reporting this gap.
