### ISSUE TITLE
[QUESTION] Difference between Update and Read-Modify-Write

### ISSUE THREAD

**Issue by giannisgrigorakos** [brianfrankcooper/YCSB#1461]
I can't wrap my head around the difference between those two operations in the workloads. What I mean is in order to update a record you have first to find it (read) the modify it and the write it again in the database. The documentation of the core workloads isn't helpful enough. How are those 2 different operations?

**Comment by busbey** [comment]
the update workload does not presume you read the original record first. it's writing fields for a record that already exists; oftentimes writing only a subset of the total fields for that record. Some data stores need to read the underlying record in order to reconcile what the final record should look like, but not all do.

the read-modify-write workload expressly reads the record from the underlying datastore and then writes an updated set of fields for that record, which effectively forces all datastores to read the underlying record prior to accepting a write for it. At the moment we use a random delta for the write rather than some value derived from the current record (say incrementing a counter). That can make the workload a bit harder to follow since the starting read seems unnecessary.

Does that help? Would it help if I added this to the [core workload descriptions](https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads)?

**Comment by giannisgrigorakos** [comment]
Ohh i get it now! Yes if you could include this in the docs that would be great. I wasn't aware that some databases don't need to read in order to update. Thank you very much for your time!

**Comment by busbey** [comment]
okay I've updated the wiki page with this description.
