### ISSUE TITLE
How to test goleveldb by using ycsb？ 🆘

### ISSUE THREAD

**Issue by zhangkanqi** [brianfrankcooper/YCSB#1478]
Now I have done "go get github.com/syndtr/goleveldb/leveldb"，and I need use ycsb to test goleveldb. But ycsb don't support goleveldb, so I need to rewrite the code of ycsb. Unfortunately, I have no idea how to rewrite code, could someone help me? !🆘

**Comment by busbey** [comment]
Our guide for adding a new storage system is over here:

https://github.com/brianfrankcooper/YCSB/wiki/Adding-a-Database

I see now it needs some cleaning, but the basics are correct. You'll essentially create a Java class that extends `site.ycsb.DB` in order to connect how YCSB talks about storage operations with how goleveldb talks about them. You will need a Java client library that can work with the storage system.
