### ISSUE TITLE
[QUESTION] Difference between   "load"   and    "run"   under 100%  Insert workload ?

### ISSUE THREAD

**Issue by nebofeng** [brianfrankcooper/YCSB#1494]
**ycsb：ycsb-hbase20-binding-0.17.0**
**hbase： 2.0.0.3.1**

I have two workloads: 100% write workloada  and 100% read workloadb

**workloada**    
```
recordcount=10000000
operationcount=10000000
workload=site.ycsb.workloads.CoreWorkload
fieldcount=100
fieldlength=10
readallfields=false
writeallfields=false
fieldlengthdistribution=constant
table=usertable
columnfamily=f1
measurementtype=raw
timeseries.granularity=1000
readproportion=0
updateproportion=0
scanproportion=0
insertproportion=1
requestdistribution=zipfian
```
**workloadb**  
```
recordcount=10000000
operationcount=10000000
workload=site.ycsb.workloads.CoreWorkload
fieldcount=100
fieldlength=10
readallfields=false
writeallfields=false
fieldlengthdistribution=constant
table=usertable
columnfamily=f1
measurementtype=raw
timeseries.granularity=1000
readproportion=1
updateproportion=0
scanproportion=0
insertproportion=0
requestdistribution=zipfian
```

I think "load" and "run" are the same  on 100% insert workload,    "run"can be executed directly without load. 
in order to reduce the time of loading data.  i did the following to test  100% insert and 100%read
Operation 1:
   Run workloadb  after load workloada ： correct
      
Operation 2:
  Run workloadb  after run workloada  ： run workloadb is not  correct
     
ErrorInfo：
```
25927.6 current ops/sec; est completion in 6 minutes  **READ-FAILED** count: 259337, average latency(us): 3367.47
[OVERALL], RunTime(ms), 203882
[OVERALL], Throughput(ops/sec), 49047.97873279642
[TOTAL_GCS_PS_Scavenge], Count, 23
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 10425
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 5.113251782894027
[TOTAL_GCS_PS_MarkSweep], Count, 1
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 44
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.021581110642430425
[TOTAL_GCs], Count, 24
[TOTAL_GC_TIME], Time(ms), 10469
[TOTAL_GC_TIME_%], Time(%), 5.1348328935364576
[READ], Total Operations, 0
[READ], Return=NOT_FOUND, 10000000
[CLEANUP], Total Operations, 192
[CLEANUP], Below is a summary of latency in microseconds:, -1
[CLEANUP], Average, 74.50520833333333
[CLEANUP], Min, 0
[CLEANUP], Max, 10457
[CLEANUP], p1, 0
[CLEANUP], p5, 0
[CLEANUP], p50, 3
[CLEANUP], p90, 12
[CLEANUP], p95, 15
[CLEANUP], p99, 2611
[CLEANUP], p99.9, 10457
[CLEANUP], p99.99, 10457
[READ-FAILED], Total Operations, 10000000
[READ-FAILED], Below is a summary of latency in microseconds:, -1
[READ-FAILED], Average, 1925.4283809
[READ-FAILED], Min, 146
[READ-FAILED], Max, 1499969
[READ-FAILED], p1, 257
[READ-FAILED], p5, 303
[READ-FAILED], p50, 509
[READ-FAILED], p90, 1247
[READ-FAILED], p95, 1832
[READ-FAILED], p99, 30035
[READ-FAILED], p99.9, 208739
[READ-FAILED], p99.99, 686019
 ```

Question1: 
   If i want to test workloada and workloadb，  is  operation1  correct？

Question2: 
  Why workloadb in  operation2 cannot be performed. What is the differences between "load" and "run" under insert workload？

**Comment by nebofeng** [comment]
@busbey :smiley:

**Comment by allanbank** [comment]
The load phase is used to create the seed records for the subsequent operations (read, update, scan, etc.) For an insert workload it also ensures that the store of the records has existing records stored and indexed that have to be managed in addition to the new records.

For insert operations the CoreWorkload makes sure that the 'run' phase generates ids for the records that are not part of the 'load' phase.

For the other operations the workload ensures that the record already exists (assuming the load phase has been run).

What you are seeing is that the load is still needed because the ids of the documents it inserts are assumed to be present for the read operations.

Put another (more formal?) way:
* The load generates records with a set if ids:'L.
* The run generates records with a set of ids: R.
* The intersection of L and R is the empty set.
* The read operation reads records based on the ids in L.

**Comment by nebofeng** [comment]
Ok i get it now! Thank you very much for your time!
