### ISSUE TITLE
Delete workload

### ISSUE THREAD

**Issue by vreniers** [brianfrankcooper/YCSB#222]
Is there a way to execute a workload which benchmarks delete operations?
In the default workload files I can only see readproportions, updateproportions etc. but
no field for an amount of delete operations?

**Comment by cmatser** [comment]
No, but you can add one fairly easily.  I did this, not because I wanted to measure deletes, but because I wanted to delete the records that I inserted during my insert runs so that I could start with the same data set for each run.  Each DB implementation is suppose to implement the "delete()" call.  So, I added a "deleteproportion" property in my local CoreWorkload.java to call the delete() method.  I also had to update my delete() method to make sure I deleted the specific records for my implementation.

I don't believe deletes are measured often because with these types of data stores, you typically never delete.... or you don't really care about the delete performance.  These stores are optimized for high scale reads.  However, everyone has there own needs.  So, I don't mean to suggest yours is invalid.  Good luck with your benchmarking.

Chrisjan

**Comment by vreniers** [comment]
Okay, thanks for the info. I'll have to take a look at this approach.
I completely agree with you though that deletes aren't really of importance with most NoSQL data stores.
But it is something I'd thought I could benchmark.

**Comment by busbey** [comment]
@vreniers if you're still interested in adding a delete workload let us know.

**Comment by vreniers** [comment]
Hi, I'm not going to add the delete workload. 
I've already completed my benchmark without it.
And it's like you said, the delete performance isn't that important.

**Comment by busbey** [comment]
sounds reasonable. thanks for getting back to me.
