### ISSUE TITLE
redis cluster is ready in redis 3.0.0 , when should YCSB support redis cluster?

### ISSUE THREAD

**Issue by SmileCaoJ** [brianfrankcooper/YCSB#233]
redis 3.0.0 is ready now,  redis cluster is supported. 
when should YCSB support redis cluster?

**Comment by busbey** [comment]
we'd be happy to add redis cluster support if we can find someone from the Redis community to add a datastore binding.

**Comment by YacineTALEB** [comment]
Hello,

Any updates on support for Redis cluster ?

**Comment by busbey** [comment]
I don't believe anyone has volunteered to add it yet. Are you interested in adding it?

**Comment by YacineTALEB** [comment]
I will dedicate some time for it, but not immediately.

**Comment by busbey** [comment]
Excellent! Let us know if you need any help with how things work.

**Comment by castroflavio** [comment]
Hi guys. 

I've done [this adaptation to work]([url](https://github.com/castroflavio/YCSB/commit/9fcd3c17b101c19f475b4f0c4ea828847abb9f51)) with a Redis Cluster using Jedis.

It currently works if the cluster was setup correctly.

**Comment by busbey** [comment]
Redis cluster support was added as of release 0.14.0. Please see the ["Provide Redis Connection Parameters" section of the README for Redis](https://github.com/brianfrankcooper/YCSB/tree/0.14.0/redis#4-provide-redis-connection-parameters).

Please note that the "cluster mode" feature wasn't specifically tested for that release, so it is still considered "experimental." We'd love feedback that someone has successfully used it so that we can move it to supported.
