### ISSUE TITLE
Memcached in YCSB framework

### ISSUE THREAD

**Issue by bigbes** [brianfrankcooper/YCSB#326]
I can add Memcached, if it's interesting for someone. There are already two key-value in-memory stores (Redis and Tarantool), stores that can't use `scan` or stores that can operate with memcached protocol, so i think this'll be interesting.

**Comment by busbey** [comment]
there was a PR for a memached implementation a while back. might be worth seeing if it's viable. If you can't find the individual PR for the implementation, I know there's one on #98 from the thumbtack fork, but the current state of me getting that to a mergable state has all of thumbtack reverted.

if you prefer starting fresh instead of finding that older code, that's fine by me as well.

**Comment by paulie-g** [comment]
:+1: , definitely interesting and viable now that memcached supports excluding records from lru handling (5 years late). I don't know what is available memcached-client-wise in javaland, but keep in mind that choice of client, protocol (classic or binary) and server threading model are very significant for characterisation. UDP performs much better than TCP for a single-threaded server, but the trade-offs with udp+threading are unclear (to me). Also, If I had to guess, the ycsb client might well bottleneck before memcached so that's worth looking out for.

**Comment by bigbes** [comment]
@paulie-g to be honest, while testing tarantool/redis http://tarantool.org/benchmark.html - i've ran into performance bottleneck as you may see on the graphics. It's needed to start a couple of YCSB clients (using https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload-in-Parallel)

**Comment by paulie-g** [comment]
Yes, that makes sense. How close to wire-speed did you get? I wouldn't be surprised if you managed to get to a place where bandwidth or packet rate were the limiting factor.

Configurable L4 and L7 protocols for the memcached tests would be great.

p.s. Nichego, u busurman-imperalistov s russkim huzhe chem u tebya s angliyskim ;)

-pasha

**Comment by bigbes** [comment]
@paulie-g Problem wasn't in the bandwidth, but in CPU. Server was 16-cpu xeon... Maybe i did something wrong?

**Comment by busbey** [comment]
We have a memcached binding now. Looks like the ref to this issue didn't get parsed as closing it.
