### ISSUE TITLE
Why does YCSB -threads <big> not cause a big load average?

### ISSUE THREAD

**Issue by pbgalvin** [brianfrankcooper/YCSB#349]
Wondering if I'm pushing my server to use all its resources.
Running YCSB against mongodb on the same server.
Definitely get larger value with "-threads 25" than with "-threads 1", but the load average on the server only increases from about 2 to about 4 - would expect it to be much larger.

Perhaps there is some bottleneck keeping the threads from running, but can't spot what it is.  Thanks for any ideas.

--Peter

**Comment by busbey** [comment]
yes, there are definitely known limitations on the current client caused by internal synchronization. There are some fixes coming in #98, but that's still a bit off.

The current practice is to run additional client processes when you need to generate more load. see [the docs page on running on multiple clients](https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload-in-Parallel).

**Comment by pbgalvin** [comment]
Ah thanks and thanks for the pointer.
Is there a pointer to info on how to have multiple YCSBs on multiple servers run their tests against a single DB on a single server?

**Comment by busbey** [comment]
there's just the wiki page I linked earlier. work on providing something more user friendly is being discussed on #255

**Comment by pbgalvin** [comment]
okay thanks.
