### ISSUE TITLE
YCSB operations start/end

### ISSUE THREAD

**Issue by ghost** [brianfrankcooper/YCSB#415]
Hi. Is it possible to get start and end timestamp of each operation (read,insert,update) during YCSB client execution? I'm running an experiment on MongoDB by using YCSB while monitoring system resource utilization by Collectd and later storing monitoring results in InfluxDB time series data base. Later, with comparing timestamps I can infer each operation corresponding utilized system resources.  

Thanks.

**Comment by busbey** [comment]
we don't currently export (or even keep) information like that.

with the problems of e.g. coordinating time, maybe we'd be better off integrating something like [Apache HTrace](http://htrace.apache.org/) so that you can at least get coordinated time spans local to each machine you're monitoring?

**Comment by hsalahi** [comment]
@busbey Thanks for your hint. I looked up Apache HTrace. It's a great tool but just dedicated to HBase. Is there such a tool for MongoDB

**Comment by busbey** [comment]
Apache HTrace is a general purpose distributed tracing tool, it is not dedicated to HBase. It does happen to be the one HBase currently uses, but that's largely because there aren't a whole lot of options around (there's essentially HTrace and Zipkin). One "cost" of HTrace is that individual client drivers need to adopt it for it to be useful across the stack.

I don't know of any internal tracing framework used by MongoDB. If folks know of one, then I'm happy to find a way to make the mechanism used by YCSB pluggable.

**Comment by busbey** [comment]
this is available via htrace support as of YCSB 0.9.0 and should still be possible with whatever is used as a part of #1156
