### ISSUE TITLE
MongoDB batching > 1 not accurate

### ISSUE THREAD

**Issue by daschl** [brianfrankcooper/YCSB#522]
Hi folks (@allanbank),

I looked at the mongo source and saw there is a batching argument in there. If you set it to > 1 it will write it into a list and only if the batch value is reached will write it to mongo.

After thinking about it, isn't that incorrect? Since YCSB will "measure" the writing into an array list and not account for the actual response time which is when the end of batch is done? If so, I think this should be removed because it skews the results.

What do you think?

**Comment by daschl** [comment]
For reference, I think this call will be taken into account for the measurement, which I think is not accurate: https://github.com/brianfrankcooper/YCSB/blob/master/mongodb/src/main/java/com/yahoo/ycsb/db/MongoDbClient.java#L273

With real batching the time measured needs to be when insert is called until the point the end of batch returns, not when its added to the array list.

**Comment by kruthar** [comment]
@daschl - thanks for bringing this up.

I think in general being able to batch on inserts could be very useful in cases where you are not concerned with performance of the data loading, and only concerned with performance of running workloads of reads, updates, scans, etc. But, as you pointed out, the way that batching is being handled means some insert operations are simply an add to an array, while others are actual batch inserts. This will cause confusing or misleading performance results.

I looked around a little bit to see if any other bindings were attempting batch loading, the only other one found was possibly the Accumulo binding. IMHO, the current insert operation should not be attempting to do batch inserts. To do that properly, with more accurate performance reporting, a new batch insert operation should probably be created so that a batch of records are passed to the db client to be inserted and the entire operation of doing that can be measured.

When looking through the code you linked, it also looks like that if your batch size is not a perfect factor of your operation count then you may actually miss the inserts that are left in the batch array at the end of the load, which is an issue.

**Comment by daschl** [comment]
Exactly - I think proper batch APIs need to be added to YCSB so this type of workload can properly be implemented. For now I think removing this type of "batching" would be best.

**Comment by allanbank** [comment]
@daschl @kruthar -

I have never been happy with the batching being in the driver but it can make the 'load' phase of the test much faster.

Now that we have a Status class my plan was to change the return value of the insert from "OK" to "BATCHED" in the case it is just added to the batch. The batch commit would then get a "BATCH_COMMITTED" status. That will make sure that two operations are distinguished and allow users to collect metrics on the two different operations.

While I agree a "real" batch API would be better adding the distinct status values will be much easier and would not exclude a batch API in the future.

Thoughts?

Rob.

**Comment by kruthar** [comment]
I think that could work, the goal being to be sure users understand what is really going on with the measurements. That should include making sure that the batch and operation count factor thing is looked into.

**Comment by daschl** [comment]
Yes, while not optimal I think this can be a great first step to at least fix the correctness of the latency measurements themselves.
