### ISSUE TITLE
[MapKeeper]How to test the real performance?

### ISSUE THREAD

**Issue by sktzwhj** [brianfrankcooper/YCSB#573]
Dear all, 

I am benchmarking levelDB and my own database engine by YCSB recently. But I am confusing because I have no idea how to get the real performance. My experiment configuration is like the followings, 

Server: ThinkPad T450s, i7 5600u, 8GB RAM, 1TB HD
Client: MacBook 13, i5 5257u, 8GB RAM, 256GB SSD
Network: 10M/100M point to point LAN.

But the write performance I got is only 1600 ops/sec. It is obviously impossible. LevelDB should have better performance. Even when I benchmarked MapKeeper/LevelDB on only one T450s(both server and client on it), I got 25K ops/sec.  I noticed that the CPU/RAM/Network on both server and client were nearly free, the latency of network is only 0.4 ms.  so what's the matter? Could (@brianfrankcooper) or anyone help with this? Thanks!

**Comment by busbey** [comment]
what version are you using? how many client threads?

**Comment by sktzwhj** [comment]
I am using 0.6.0. Client thread is 4.

**Comment by sktzwhj** [comment]
Do I need more machines to be clients?

**Comment by busbey** [comment]
which RC for 0.6.0 are you using?

you should increase the number of client threads first. you could also try running multiple clients on the same machine if you are pegging any resources.

**Comment by sktzwhj** [comment]
Sorry, what do you mean by RC? I tried to use 8 threads for each client and run 2 clients on my laptop, the peak performance is around 8k now. But still lower than it should be.

**Comment by busbey** [comment]
Version 0.6.0 hasn't been released yet. There are two pre-release versions (0.6.0 Release Candidate 1 and 2) that are currently in test. Generally speaking, you should avoid using pre-release versions for any kind of testing. Our latest stable release is [0.5.0](https://github.com/brianfrankcooper/YCSB/releases/tag/0.5.0), and you should probably use that until 0.6.0 has an official release. I doubt this is related to your issue though.

I didn't think we had leveldb support, so I'll need to figure out what you're running in order to see how the 8k record operations/second corresponds to leveldb operations.

How did you come up with the 25K number? If going from 4 to 16 threads got you more than a 4x improvement, then you might still need to increase the number of clients.

**Comment by sktzwhj** [comment]
I am not sure, I git clone the code from github directly. The 25K number is gotten from deploying both the server and client on the same machine. YCSB doesn't have the support for levelDB but for mapkeeper. I am using the leveldb in mapkeeper to benchmark now.

**Comment by busbey** [comment]
Just to clarify, are you saying if you run the YCSB client on the same machine as leveldb (but keep all other parameters the same) then you get 25k rows/sec reported by the YCSB client using 4 threads?

**Comment by busbey** [comment]
bump. still working on your questions?

**Comment by sktzwhj** [comment]
Thanks for your concern. It has been solved. I made a mistake. I forgot to consider the TCP transport latency. For 100Mbps network. If the latency is 0.05ms, it seems that the result performance could not be better than 1/0.00005 = 20000. And according to test existing db-bindings, I find most db faces severe performance decreasing in multi-client situation.

**Comment by busbey** [comment]
Happy to help!
