### ISSUE TITLE
Running against Cassandra on a machine with better hardware seems to take longer.

### ISSUE THREAD

**Issue by Hadi14** [brianfrankcooper/YCSB#584]
Hi
 i load and run the same recordcount on two machine (machine1: ci3 2G Ram , machine2:16core 32G Ram) but machine2 was slower , for example  run time with 2000 record on machine1 was 5s but on machine2 was 6s , why?

**Comment by kruthar** [comment]
Hi Hadi - couple questions about your benchmark:
* Which db are you using and is the db installed on the same machine as YCSB is running?
* How many times did you run the benchmark on each machine type? What is the variance in your results?

**Comment by Hadi14** [comment]
my db is cassandra
as i said for machine1 run time was 5 second but for machine2 was 6 second.

**Comment by kruthar** [comment]
OK - a few things. 

1. It is generally advisable to run benchmarks several times and compare the results. You want to do this so that you can see if your results are consistent or not. So, I would suggest you run your benchmark on each machine a few times to make sure that you have consistent results and can build an average run time for each.
2. Runtimes of only 5-6s are tiny workloads. When you work with workloads that small ANY sized machine will likely perform at the same speed, there just isn't that much work to do. So, I would suggest you increase the size of the workloads.
3. Yes, 6 > 5, but not by much. As I said before your workloads are tiny, a difference in 1 second is not a good indicator that one machine is truly faster than the other.

**Comment by Hadi14** [comment]
you say correct but these two machine according their hardwares are not comparable
i bench mark with larger size of record count and will say result.

**Comment by Hadi14** [comment]
i do benchmark with 128000 record on machine1 114s on machine2 110s , i think ycsb on machine2 use only 1 core of cpu but while machin2 have 32G ram.

**Comment by kruthar** [comment]
Can you post all of the parameters of the workload you are running?

**Comment by Hadi14** [comment]
bin/ycsb load cassandra2-cql -p hosts="localhost" -p recordcount=2000 -P workloads/workloada > ~/result/workload_res.txt

 bin/ycsb run cassandra2-cql -p hosts="localhost" -p operationcount=2000 -P workloads/workloada > ~/result/workrun_res.txt

**Comment by kruthar** [comment]
One note, if you are raising the recordcount, you still need to provide the correct recordcount in addition to the operationcount to the ```run``` command, so that the full range of keys are available for the operations.

I'm assuming that when you set the recordcount to 128000 that that means the operation count was also that value? You might want to rerun with both operationcount and recordcount being set on the ```run``` command.

At this point we won't really be able to tell you why one system is performing above another. We know nothing about the two systems you have setup. One thing you could do to make sure it is not YCSB as the bottleneck is to do a ```run``` command with a very high operationcount against the ```basic``` db. Compare the results you get from the two machines.

**Comment by busbey** [comment]
less than 2 minutes is still not enough time to get out of the JVM's warm up. I suggest you start with a run of 1 or 2 million records and operations.

note that by default YCSB only uses a single thread per client. you have to specify the {{-threads}} option to get more.

**Comment by Hadi14** [comment]
@kruthar if i got your opinion correctly , well generally we set recordcount on Load phase the same of operationcount on Run phase.

**Comment by Hadi14** [comment]
@busbey i think at least not should Runtime on machine2 bigger than Machin1 but while i benchmark with number of threads.

**Comment by busbey** [comment]
there are too many factors to say, especially with such a short run time. Frankly, I'm surprised you can run both a Cassandra server and a YCSB client on a machine with 2GiB of memory.

**Comment by Hadi14** [comment]
with 16 thread on machine2 run time was 13s , but loadtime is 76s that it is very much for this machine while on other machine Loadtime was 46s.

**Comment by busbey** [comment]
What does "cors" mean in this context?

76s is very short. are you doing the larger number of records / operations I suggested earlier?

please include the actual command lines you use when referencing the time it takes for particular runs.

**Comment by Hadi14** [comment]
ok , core of cpu
even i load on machine2 got this error(time out ) :
<code>com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency ONE (1 replica were required but only 0 acknowledged the write)</code>

Load command :
<code>bin/ycsb load cassandra2-cql -p hosts="localhost" -p recordcount=1024000 -P workloads/workloada > ~/result/workload_res.txt</code>

**Comment by busbey** [comment]
> even i load on machine2 got this error(time out ) :
> com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency ONE (1 replica were required but only 0 acknowledged the write)

This looks like misconfiguration of your cassandra cluster. you should first ensure your Cassandra cluster is correctly set up. Please see [the cassandra website](https://cassandra.apache.org) or [their mailing list](http://mail-archives.apache.org/mod_mbox/cassandra-user/) for help doing that.

>Load command :
bin/ycsb load cassandra2-cql -p hosts="localhost" -p recordcount=1024000 -P workloads/workloada > ~/result/workload_res.txt

You are still only using a single thread to do the loading. you must pass `-thread n` to run with more threads, e.g. `-thread 4` will have YCSB launch 4 threads in the client. These additional threads are how you get YCSB to make use of more cpu cores (though they may not due to e.g. blocking on IO to the datastore).

**Comment by Hadi14** [comment]
-thread X  only use for run phase correct?

**Comment by cmatser** [comment]
What are you trying to accomplish with YCSB?  Are you really trying to see if machine A is faster than machine B?  Based on the specs, I would say machine B is faster.  You don't need YCSB for that.

So, why is your YCSB results not showing that?  Well, you're not using it right.
1) Your loads are too small.  You should have a run that lasts at least 10-20 minutes in order to draw some meaningful conclusions.  (Even that is an arbitrary number... I would look at throughput and see how long it takes for throughput to reach a steady state and then run for some meaningful amount after that.)
2) You are running single threaded.  On an 16 core machine and you have a single threaded operation, then the other 15 cores are doing a lot of just waiting around.  So, I wouldn't expect very different results assuming other factors are similar like cpu speed, number of other processes running, etc.

I believe you should be trying to simulate your real world use cases.  How many concurrent connections do you expect to handle (this should be your thread count).  How many operations a day do you want to be able to perform?  How large will your data set be?

Then setup your db and run.  And make your observations.  Generally, I disregarded the results of a load phase because my use cases were more read heavy with some inserts and a few updates.
-Are you trying to see if the machine can handle your real world use case?  While YCSB is running, check your machine statistics to see if RAM is being over or under utilized.
-Are you trying to see what different configurations of cassandra will yield the most optimal results?  Then make the changes to cassandra, run again, and observe.
-Are you trying to see if a different database like mongo will work better?  Then, swap out the db, change the YCSB binding to mongo, run and observe.

I hope you see where I'm going here.  Be deliberate with your calculations.  This is going to take longer than just a few seconds.  Sorry, for being gruff with this post.  Feels like tough love is needed. :)

**Comment by Hadi14** [comment]
so, even though on machine2 there is a good size of RAM , on your opinion what is reason to slower than machine1  even 1s?

**Comment by busbey** [comment]
The amount or kind of memory on the machines is almost certainly immaterial given the workload sizes you've been using.

Please go back again to @cmatser's starting question. You must begin your investigation by deciding what it is you hope to understand.

**Comment by Hadi14** [comment]
ok , 
if we have for examlpe 8 core of cpu , load action is overall all cores? or only one core?

**Comment by busbey** [comment]
Any further questions on this one @Hadi14?

**Comment by busbey** [comment]
Closing as stale. If you're still working on this issue please reopen.
