### ISSUE TITLE
Increasing Number of VMs decreases Cassandra Throughput. What can be reason?

### ISSUE THREAD

**Issue by pushpendrachaturvedi** [brianfrankcooper/YCSB#595]
Hello,

I am using YCSB benchmarking tool to benchmark Cassandra cluster.
I am varying the number of Virtual machines in the cluster.
I am using 1 physical host and I am using 1,2,3,4 virtual machines for benchmarking(as shown in attached figure).

The generated workload is same all the time Workload C 10,000,00 operations, 10,000 records
Each VM has 2 GB RAM, 20GB drive

Cassandra- 1 seed node, endpoint_snitch- gossipproperty
Keyspace YCSB- Replication factor 3,

The problem is that when I increase the number of virtual machines in the cluster, the throughput decreases. What can be the reason?

By definition, by increasing compute resources(i.e virtual machines), the cluster should offer better performance, but the opposite is happening as shown in attached figure. Kindly explain what can be the probable reason for this? I am writing my thesis on this topic but I am unable to figure out the reason for this, please help, I will be grateful to you.

[VMallUbuntu.pdf](https://github.com/brianfrankcooper/YCSB/files/102084/VMallUbuntu.pdf)

**Comment by kruthar** [comment]
Can you answer a few questions:

1. Can you provide the YCSB commands you are running as well as the workload file (if you have made any changes to it)
2. Have you done anything to guarantee that with multiple VM's Cassandra is configured properly with multiple hosts?
3. On which machine/host is YCSB being run from.

>By definition, by increasing compute resources(i.e virtual machines), the cluster should offer better performance

Unfortunately, this is not always the case. In general, increasing compute on a single VM can increase performance on that single VM. But increasing compute of a cluster by adding multiple VM's is not a sure fire way to increase performance. You have to take into account how much work databases now have to do like route requests across the nodes, aggregate results from multiple nodes, depending on replication you could now be spending time replicating data across nodes, etc. There are a lot of things you have to think about when using a distributed system vs. using a single node system.

Another consideration is if YCSB is running on a single thread the entire time, and Cassandra on a single node is not topping out with the workload you are using, than you probably would not expect to see a lot of performance increase by increasing nodes because your single node cluster is perfectly capable of handling the load.

You should also consider the performance of each machine in terms of cpu usage, memory usage, i/o, network, etc at these different cluster sizes. These types of information may give you some insights on why you are seeing these performance differences. YCSB output alone is not sufficient definitively say why one system outperforms another.

**Comment by cmatser** [comment]
+1 Agree with everything @kruthar said.

I like your included graph.  The results are interesting, but I think you need another graph that shows throughput response in relation to load (number of client processing threads).

You don't mention the number of threads you are running to process your workload.  If I assume you are running single threaded, then the graph makes perfect sense to me.  You've added more nodes to the server cluster just to serve a single client.  You've increased the complexity of the server which is going to add delay in the manner @kruthar discussed.

Adding more VMs to the cluster should help with performance under heavy load.  I hope I'm right in assuming you have not exercised enough threads to really put a load on your cluster.  Only then I believe will you see the gains of having more nodes in the cluster.

Good luck!

**Comment by busbey** [comment]
Still working on analyzing this situation, @pushpendrachaturvedi?

**Comment by pushpendrachaturvedi** [comment]
Thanks to everyone for your replies they were useful in analysing the situation. But i think the problem was not due to YCSB but it has risen due to resource contention between VMs of same physical host as stated here http://stackoverflow.com/questions/34970526/increasing-number-of-vms-decreases-cassandra-throughput-what-can-be-reason. I am thus closing the issue. thanks again.
