### ISSUE TITLE
Performance of Cassandra

### ISSUE THREAD

**Issue by Mike-Petersen** [brianfrankcooper/YCSB#611]
Hi,
we made several tests with YCSB comparing mongodb and cassandra in our current setup. At first we wanted to compare just mongodb on red hat enterprise linux 6/7. But also added testing wired tiger and cassandra.

Cassandra is a pretty new technology for us that we are currently testing. In general we had the following settings:

```
recordcount=6000000
operationcount=100000000
threads=100
fieldlength=250
measurementtype=timeseries
core_workload_insertion_retry_limit=10000
```

We also tested with a record count of 2.000.000 and 3.000.000. We used workload a, b and f.

All machines there run on identical nodes. We tested virtual servers (like our current infrastructure) and local hard drives on a dedicated machine.

For cassandra we sometimes had timneout during the load phase. That is why we added the "core_workload_insertion_retry_limit=10000" option.

We also used different amount of nodes in our tests. We tested:
- a single mongodb node
- three mongodb nodes
- 1 cassandra node
- 3 cassandra nodes
- 4 cassandra nodes
- 5 cassandra nodes

On cassandra nodes we tested replication factor 1 and 2.

In all our tests cassandra was much slower than mongodb. In general we did not expect this, especially if we increase the nodes in cassandra. But in our case it does not seem to be the case. We already added a few general performance tips. But due to our infrastructure had not splitted the commit and data directory to separate disks.

We repeated most of the tests but in the end concentrated on workload a. Cause the performance difference was on every workload.

In the web we found tests with YCSB there cassandra is performing quite good. So in general our question would be: Are we doing something wrong?

Thanks

Regards
Mike

**Comment by kruthar** [comment]
How much slower is "much slower", can you provide a sample of your metrics that shows the performance difference?

I would suggest doing load tests over Cassandra that are much smaller then what you posted here. Small enough that you don't get any hiccups during the load phase. Then incrementally build up to the workload you specified. Knowing how the system performs as the workload scales up can be pretty enlightening. 

Also, have you looked into what the machine performance metrics look like during your tests (cpu, memory, etc) This may tell you how hard the vms are working. And whether all machines in your cluster are working the same amount or not.

Are you using the ```cassandra2-cql``` client? If so, you can fiddle with the consistency and connection settings detailed here: https://github.com/brianfrankcooper/YCSB/tree/master/cassandra2. Those can have some level of impact.

Since Cassandra is new to you, have you ensured that your cluster is configured properly? Are the nodes talking to each other properly?

**Comment by Mike-Petersen** [comment]
We are using the cassandra2-cql client. We have left the consistency level at the default of ONE.
We also installed the cassandra ops center and looked into the "best practices". I think we might not be optimal but have implemented some basic performance tips.

In ops center and in the node tool there seems to be no problem with the connection between the nodes. Everything seems to be running smoothely.

An example of the runtime is like this:
- mongodb rhel6 mmap 35850s
- mongodb rhel7 mmap 36769s
- mongodb rhel7 wired tiger 49831s
- cassandra 3 nodes 100367s

So in this case cassandra needed twice the time from the mongodb with wired tiger. On the other tests is was approximately the same.

We used a larger working set so that every db has to use the disk and can not hold everything in memory. It is also running for a longer period so i think it should have enough time to warm up or not?
We already tested smaller working sets but the difference in the performance does not seem to be affected by that.

**Comment by cmatser** [comment]
Take a look at [How not to benchmark Cassandra](http://www.datastax.com/dev/blog/how-not-to-benchmark-cassandra) for some tips.

I did my performance testing with 1, 3 and 9 nodes.  We had 1 million records and we tried different replication factors and write durability.  Our operations were read heavy and we took samplings at multiple thread counts from 1 to 1000.

We did not do loads with YCSB as we used our own schema and data values.  (I had to alter YCSB to work with our schema.)

For our results, we looked at throughput values rather than overall time, but I don't mean to suggest that overall time is not a valid metric.  We also looked at latency which confirmed our throughput findings.  We did find cassandra to perform better than mongo in our setup.  Though for development projects, I like mongo for its ease of install and use.

We did our benchmarks in 2014.  While mongo was no slouch in the numbers, I am surprised that your cassandra numbers don't compare so favorably.  Make certain you really are comparing apples to apples... number of nodes, same machine configurations, replication factors, write durability, etc.

Chrisjan

**Comment by cmatser** [comment]
Oh if you're concentrating on load times, then take my performance results with a grain of salt as we were concentrating on read performance.

Chrisjan

**Comment by Mike-Petersen** [comment]
We time is the overall run time. So the time it needed to process all 100.000.000 operations in the run phase.

Yes we are also suprised. Especially cause we found benchmarks with YCSB that had a different result. The only thing i do not know is if it was made with cassandra2-cql or the previous one.

**Comment by vfunshteyn** [comment]
I would recommend trying to rule out the client side as the primary bottleneck. You may want to monitor load/CPU usage on the box where you run your client(s) and go from there. One thing that does stick out in your configuration is threads=100. It's probably best to limit it to a more reasonable value (# cores * 4 or so), unless your projected use case anticipates that level of concurrency within a single JVM, funneled through a single DB endpoint (how YCSB drivers are mostly implemented).

**Comment by cmatser** [comment]
Cassandra's DB connection object supports pooled connections and that size can be controlled with the "cassandra.coreconnections" and "cassandra.maxconnections" properties.  You might want to check your values and correlate them to your thread size.

**Comment by vfunshteyn** [comment]
@cmatser: Good point re: connection pool properties. Unfortunately, the client code hardwires those to `HostDistance.LOCAL` (and I'm not sure if this is the right parameter to use).

**Comment by kruthar** [comment]
@Mike-Petersen 

>mongodb rhel6 mmap 35850s
mongodb rhel7 mmap 36769s
mongodb rhel7 wired tiger 49831s
cassandra 3 nodes 100367s

Are these times for MongoDB on a 3 node cluster? (looks like Cassandra is on 3 nodes).

I would suggest designing a much smaller test that eliminates a lot of places of potential cause for slowdown to Cassandra:
- Single node Cassandra and Mongodb clusters
- Single threaded YCSB workloads
- Data size that fits in memory for both MongoDB and Cassandra
- Operation count that runs for 10 minutes or more

After you have eliminated a lot of moving parts and variables you should get a good baseline for how MongoDB and Cassandra compare. Then build up your benchmark one variable at a time. EX change ONLY the number of nodes in both clusters (leave EVERY other aspect of the benchmark the same). Or change ONLY the number of threads on YCSB.

Make incremental changes and see how the results change for each database.

When you start to scale up the MongoDB and Cassandra clusters make sure you are comparing them with as similar architectures as possible. Things to think about here are:
- having the same replication factor in both databases
- having the same number of nodes in both databases
- having the same resources allocated to the nodes (cpu, memory, etc) These types of things can often be restricted in database configuration
- having the same types of machines (VM vs dedicated hardware)

From your first post it is hard to tell if your tests between MongoDB and Cassandra have all of these factors consistent between the two.

@vfunshteyn - for the most part I think that ```HostDistance.LOCAL``` is ok in the general case. LOCAL is for same datacenter deployments between client and server. REMOTE would be for cross datacenter.

**Comment by Mike-Petersen** [comment]
Thanks for all the tips.

@vfunshteyn: We already monitored the client side and neither memory or cpu are an issue during the load/run phase.
We started with a lower amount of threads, but it was also larger than cores * 4. We thought that we could simulate 100 clients accessing the data with the thread count. We will try a lower value here.

@cmatser: We did not change this setting. What would be a reasonable number?

@kruthar: Yes, every mongodb is on a three node cluster.

We started with a setup with only one node per mongodb/cassandra cluster. Also our workingset was small enough to fit in memory on some tests. But in general it was the same result.

The machines are on the same hardware and have equal amount of cpu and memory. We also used the same amount of nodes.
Additionally we made tests with more nodes for cassandra. The replication factor in cassandra is currently smaller in our tests than the mongodb one.

**Comment by cmatser** [comment]
I can tell you that what I did was I left the coreconnections alone and set maxconnections to the thread count.

We found that performance suffers when more nodes are added at small thread counts.  The difference comes with higher thread counts.  The added nodes are able to handle a heavier load of simultaneous client requests; so throughput increases.

Perhaps mongo performance has gotten better since I tested it.  Unfortunately, I don't have access to the testbed I used before.

Good luck.

**Comment by kruthar** [comment]
Are you seeing a big performance gap on both ```load``` and ```run``` phases? I was looking at the MongoDB client readme and their example connection string has ```w=0```, unacknowledged writes which make inserts very fast (but are likely not representative of real applications).

**Comment by Mike-Petersen** [comment]
@cmatser: We now also tried i higher amount of connections (200 and 1000). It does not seem to have any effect.

@kruthar: You are right. We had w=0 in the load phase. Without it (or w=1) the load phase took longer. But cassandra still is much slower during the load phase (factor ~1.7).

**Comment by Mike-Petersen** [comment]
Every test so far does not seem to change a lot.

We experienced something strange by looking on the open connections on the cassandra machines. If we did not set the min. connections in cassandra it seems that it only uses one connection per node. We increased the min. amount and as expected a higher amount of connections per host is opened. If it is really used we do not know. It was only a single test there we investigated it (did not look onto that before), so it is not too sure to be true for every run.

Unfortunately we do not have more time to investigate this a lot further.

**Comment by mhsu0020** [comment]
I am facing the same issue as @Mike-Petersen. The YCSB MongoDB is around 6 times faster than the Cassandra2-cql implementation. MongoDB achieves about 3000 ops/s while the cassandra counterpart is around 500. However, when I run [cassandra-stress](https://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsCStress_t.html), I get around 6000 ops/s.

**Comment by risdenk** [comment]
@mhsu0020 - Can you be specific about what exactly you ran for YCSB and for cassandra-stress?

**Comment by mhsu0020** [comment]
@risdenk I'm comparing the YCSB load phase to cassandra-stress's write option. For YCSB I ran the load phase of workload A with recordcount 100k and operationcount 100k. For cassandra-stress I ran `./cassandra-stress write n=100000`

**Comment by risdenk** [comment]
@mhsu0020 which version of MongoDB and Cassandra?

**Comment by mhsu0020** [comment]
@risdenk [Datastax Distribution V3.3.0](http://www.planetcassandra.org/cassandra/) and MongoDB 3.2

**Comment by nitsanw** [comment]
the difference might be related to the fact the cassandra-stress and YCSB schemas are different?

**Comment by cricket007** [comment]
@nitsanw Sorry to dig up an old post. It should be possible to stress test [any schema](http://www.datastax.com/dev/blog/improved-cassandra-2-1-stress-tool-benchmark-any-schema).

**Comment by busbey** [comment]
anyone still looking at this for the Cassandra side?

**Comment by busbey** [comment]
closing as stale.
