### ISSUE TITLE
how to identify number of field on redis to run YCSB

### ISSUE THREAD

**Issue by Hadi14** [brianfrankcooper/YCSB#632]
Hi
when run WorkloadA on Cassandra , we should first create keyspace and table and 10 field but i run WorkloadA without create table and filed , how it run without specific table?

**Comment by kruthar** [comment]
I haven't used Redis much, so take this with a grain of salt.

Redis is a key-value store, it doesn't really have databases or tables, you can sort of think of it as a single database with a single table. So, you don't need to create a database or table first because everything goes into a single bucket.

**Comment by Hadi14** [comment]
so what is different between 10 field with less or more field ? why on cassandra is not this? can you explain more? thank you

**Comment by kruthar** [comment]
>so what is different between 10 field with less or more field ?

The number of fields YCSB uses and expects the target database to handle is configurable because it could potentially affect performance. I don't have any specific examples for you but it is easy to imagine that some databases may be slower to read if they were storing 100 fields as opposed to only storing 10 fields. The default is 10 fields, that number is arbitrary, you can choose what ever you like. Keep in mind that the number you choose may affect how you setup your target database. EX. as you point out you have to define a table with the correct number of fields in Cassandra.

>why on cassandra is not this?

I'm not sure what this question is asking. You can use as many fields as you want for your benchmark on Cassandra, you just have to make sure that you have configured the Cassandra table properly before hand.

**Comment by Hadi14** [comment]
actually my opinion is according to this link:
https://github.com/brianfrankcooper/YCSB/tree/master/cassandra2

we create table and 10 filed and next we do benchmak for example WorkloadA but for redis on this link:


we dont create any table with number of fields for benchmark https://github.com/brianfrankcooper/YCSB/tree/master/redis

when we dont create 10 filed , how to store data from workloadA to redis?

**Comment by kruthar** [comment]
Take a look at how the RedisClient actually works: https://github.com/brianfrankcooper/YCSB/blob/master/redis/src/main/java/com/yahoo/ycsb/db/RedisClient.java.

The basic concept is that the the fields are combined into a map, then hashed into a value that is stored in Redis. What you have are keys (ex. 'user1') pointing to a blog that represents a map of field names to values.

**Comment by Hadi14** [comment]
can we say Generally that is mean on workloads there are different type of field to use to different type of database (like: document store , key value , ...) and they is created for specific database to store?

**Comment by kruthar** [comment]
@Hadi14 - Yes, that is correct. Each database client in YCSB has different requirements for setup of the target database, so it is crucial to read through the specific client README's first. Cassandra's README explains how to create a keyspace and table, whereas Redis's README does not mention the need for creating any type of collection or table.

**Comment by Hadi14** [comment]
ok thank you very much @kruthar .
