### ISSUE TITLE
what is meaning of this write timeout exactly?

### ISSUE THREAD

**Issue by Hadi14** [brianfrankcooper/YCSB#654]
Hi all , very excusme
i have asked this question but i dont understand concept of this write timeout completely 
`write_request_timeout_in_ms: 2000`

can you explain for me?

**Comment by risdenk** [comment]
`write_request_timeout_in_ms` is a Cassandra configuration and not part of YCSB. You should check the Cassandra documentation and resources for help.

**Comment by Hadi14** [comment]
i know that is configuration parameter but where use it? and which document?

**Comment by kruthar** [comment]
@Hadi14 - we cannot provide you with information on ```write_request_timeout_in_ms``` because it has nothing to do with YCSB, you do not put this in any files related to YCSB. This is a Cassandra configuration and goes in what ever configuration files there are for Cassandra, I would highly suggest hitting the Cassandra mailing list or if they have a forum somewhere.

**Comment by Hadi14** [comment]
@kruthar it there is on cassandra.yaml.
