### ISSUE TITLE
Which one is more faster  : READ or SCAN ? and Why ?

### ISSUE THREAD

**Issue by amirjuve** [brianfrankcooper/YCSB#666]

**Comment by risdenk** [comment]
Read and scan have two completely different use cases typically. Read is usually random reads across the data set where you are looking up values by id or key. Scan is typically looking for records that are close to each other starting with an id or key and stopping after a certain number of records or at an end key. Some of the YCSB bindings don't support scan currently.

Some data stores are better at read than scan and others are the other way. It depends how they were designed.

**Comment by amirjuve** [comment]
would you to give an exemple ?

**Comment by risdenk** [comment]
Look at the YCSB code and notice which bindings have scan implemented. That is a good indication of which data stores don't have a good way of doing scan. Memcached is an example that performs reads well, but scan doesn't make sense for it. Issue #668 is an example of that. HBase has scans since the it can check the rowkey prefix and puts rowkeys that have the same prefix in the same region server.
