### ISSUE TITLE
memcached SCAN always fail

### ISSUE THREAD

**Issue by cimballihw** [brianfrankcooper/YCSB#668]
Hello world!

I am now running YCSB to benchmark memcached, and I have tested all the workloads (A to F) so far.
I noticed that workloade, which performs SCAN operations, will fail, mostly because all SCAN operations fail. As a result throughput is meaningless, and I can not assess this operation latency on my architecture.
Did anyone experience this before?
Thank you in advance.

**Comment by risdenk** [comment]
@cimballihw - The Memcached binding doesn't implement SCAN. Check the source code here https://github.com/brianfrankcooper/YCSB/blob/master/memcached/src/main/java/com/yahoo/ycsb/db/MemcachedClient.java#L189-L194 You are probably getting not implemented instead of actual failures. Memcached and SCAN doesn't really make sense in most cases. Memcached is basically a cache for key/value lookups.

**Comment by risdenk** [comment]
@cimballihw - did the above answer your question? Thanks!

**Comment by cimballihw** [comment]
@risdenk - yes, indeed I had a look at the source code and scan is not implemented for Memcached. However, because why all other key-value databases would use SCAN, since the search using key list is by far more efficient? is it because of memcached partitioning in slabs, which makes it slower than others?
