### ISSUE TITLE
Orientdb performance

### ISSUE THREAD

**Issue by amirjuve** [brianfrankcooper/YCSB#672]
I lunched a test of 100 000 records (workloadE), i was waiting for 30 min and the test has not yet been completed.  anyone confims this ? who tested this before ?

Thanks in advance

**Comment by busbey** [comment]
if you run with the {{-s}} flag, you can see status while things are in-progress.

**Comment by amirjuve** [comment]
Yes, 32 op/sec, is that logical ? this is really slow, can you confirm that ?

**Comment by busbey** [comment]
That is very slow. Without knowing e.g. system specs there's no way for me to guess if that's understandably slow or if there's a likey misconfiguration.

I'd recommend checking with OrientDB's user community for proper tuning tips.

**Comment by amirjuve** [comment]
i'm working with INTEL core i5, i think that orientdb is slow when it becomes to add new Vertexs

**Comment by kruthar** [comment]
There are known performance issues with the OrientDB scan operation, you can see a note about that on the readme: https://github.com/brianfrankcooper/YCSB/tree/master/orientdb.

In a nutshell the issue is that there is not a good iterator in the OrientDB to use when you ar given a startkey and a number of records to return. The current implementation uses an iterator that gets ALL records after the startkey. This is obviously not performant and so when you have large numbers of records you may see a performance decline when using scan.

**Comment by amirjuve** [comment]
Thank you @busbey  @kruthar
