### ISSUE TITLE
[MapKeeper]Testing Leveldb with errors

### ISSUE THREAD

**Issue by maplecumt** [brianfrankcooper/YCSB#675]
I'm benchmarking levelDB by YCSB recently.  And I'm using the 0.7.0. When I'm using
 `$ ./bin/ycsb load basic -P workloads/workloada`
the ycsb is ok. But when I'm using
 `$ ./bin/ycsb load mapkeeper -P workloads/workloada`
 to benchmark mapkeeper there is an error like this:
`Traceback (most recent call last):
  File "./bin/ycsb", line 259, in <module>
    sys.exit(main())
  File "./bin/ycsb", line 232, in main
    maven_says = get_classpath_from_maven(project)
  File "./bin/ycsb", line 178, in get_classpath_from_maven
    + err.output)
TypeError: cannot concatenate 'str' and 'NoneType' objects
`

What can I do?  Could (@brianfrankcooper) or anyone help with this? Thanks!

**Comment by busbey** [comment]
The mapkeeper module is currently disabled because the driver we need no longer gets published to a maven repo we can access. (See #181)

If you need to get things working locally, the instructions described on #262 should still work.

**Comment by maplecumt** [comment]
I have done the  instructions described on #262 and after doing the commad
 
 `mvn install:install-file -Dfile=mapkeeper-1.0.jar -DgroupId=com.yahoo.mapkeeper -DartifactId=mapkeeper -Dversion=1.0 -Dpackaging=jar
`

It says BUILD SUCCESS. But when I execute the command 

`./bin/ycsb load mapkeeper -P ./workloads/workloada`

here is another error:

`[ERROR] Could not find the selected project in the reactor: com.yahoo.ycsb:mapkeeper-binding -> [Help 1]
`

I am using Ubuntu 14.04. What can I do next? Thanks!

**Comment by maplecumt** [comment]
I'm now editing the file MapkeeperClient.java because I find that the functions in MemcachedClient.java or MongoDbClient.java such as read,scan,update,delete returns 'Status' which is defined in `com.yahoo.ycsb.Status` , but these functions in MapkeeperClient.java returns 'ret' which is a number returns from function 

`ycsbThriftRet(ResponseCode rc, ResponseCode zero, ResponseCode one)`

But I don't know the map between the ret number and the Status.

**Comment by maplecumt** [comment]
I edit the map between the ret number and the Status as the below:

        Status retToStatus(int ret)
            {

                if(ret == 0){

                    return Status.OK;
                }else if(ret == -3){

                    return Status.NOT_FOUND;
                }else{

                    return Status.ERROR;
                }
            }




I know that is not the best, but the ERROR skipped but here comes another error like this:


        SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
        SLF4J: Defaulting to no-operation (NOP) logger implementation
        SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.




I changed the version of slf4-api.jar, but didn't solve it. Can you help me ?

**Comment by risdenk** [comment]
You can ignore the SLF4J failed to load. Its more of a warning than anything else. YCSB doesn't have consistent logging yet so some bindings have that warning.

**Comment by maplecumt** [comment]
Thanks risdenk..

**Comment by srzmldl** [comment]
Hi,  maplecumt. 
I want to test leveldb as well.
I modify the client as well to compile successfully.
1. The author did not import Map
2. return Status conflict
3. lack a ';'

But now, when I try to  `bin/ycsb load mapkeeper -P workloads/workloada`
The exception is 
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:mapkeeper-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
java -cp /home/lab410/YCSB/mapkeeper/ycsb/YCSB/mapkeeper/conf:/home/lab410/YCSB/mapkeeper/ycsb/YCSB/mapkeeper/target/mapkeeper-binding-0.9.0-SNAPSHOT.jar:/home/lab410/YCSB/mapkeeper/ycsb/YCSB/mapkeeper/lib/mapkeeper.jar:/home/lab410/YCSB/mapkeeper/ycsb/YCSB/core/target/core-0.9.0-SNAPSHOT.jar:/home/lab410/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/home/lab410/YCSB/mapkeeper/ycsb/YCSB/mapkeeper/lib/libthrift-0.8.0.jar:/home/lab410/.m2/repository/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.jar:/home/lab410/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar:/home/lab410/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/home/lab410/.m2/repository/org/slf4j/slf4j-nop/1.6.4/slf4j-nop-1.6.4.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.MapKeeperClient -P workloads/workloada -load
YCSB Client 0.9.0-SNAPSHOT
Command line: -db com.yahoo.ycsb.db.MapKeeperClient -P workloads/workloada -load
Loading workload...
Starting test.
Exception in thread "Thread-1" java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.yahoo.ycsb.db.MapKeeperClient.init(MapKeeperClient.java:66)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
[OVERALL], RunTime(ms), 16.0
[OVERALL], Throughput(ops/sec), 0.0

**Comment by risdenk** [comment]
@srzmldl commenting on closed issues will typically not get any attention. Open a new issue instead.
