### ISSUE TITLE
StringByteIterator toArray does not return the entire byte representation of the value

### ISSUE THREAD

**Issue by ShayHassidim** [brianfrankcooper/YCSB#69]
GemFireClient convertToBytearrayMap method does not store the entire value

retVal.put(key, values.get(key).toArray());
should be:
retVal.put(key, values.get(key).toString().getBytes());

If you will run this in debug mode you will find only few bytes are actually stored in cache.
Shay

**Comment by busbey** [comment]
I think this issue comes down to incorrect handling of String <-> byte[]. In addition to #279, StringByteIterator incorrectly uses the String's character length to determine how many bytes should be made and then incorrectly pulls each character and truncates it to a byte.

That means for Strings made up of non-ascii, `toArray()` will return a smaller array than if you immediately call `toString().getBytes()` (if you don't call toString immediately then you get the wrong answer still).

**Comment by busbey** [comment]
Fixed by #288
