### ISSUE TITLE
How could I understand the workload

### ISSUE THREAD

**Issue by wuxiaomin98** [brianfrankcooper/YCSB#729]
Hi there, I have a question on understanding the workloads with different portions. I'm curious about the meaning of recordcount and operationcount. Such as for workloadb:

```
# Yahoo! Cloud System Benchmark
# Workload B: Read mostly workload
#   Application example: photo tagging; add a tag is an update, but most operations are to read tags
#                        
#   Read/update ratio: 95/5
#   Default data size: 1 KB records (10 fields, 100 bytes each, plus key)
#   Request distribution: zipfian

recordcount=1000
operationcount=1000
workload=com.yahoo.ycsb.workloads.CoreWorkload

readallfields=true

readproportion=0.95
updateproportion=0.05
scanproportion=0
insertproportion=0

requestdistribution=zipfian
```

Here the read/update portion should be 0.95/0.05. But why the readcount and operationcount are set to the same, should they be different, with portion same as 0.95/0.05?

Thanks!

Jun

**Comment by kruthar** [comment]
hi @wuxiaomin98 - first off I edited your posting to improve readability.

The `recordcount` property is how many records will be 1) inserted into your database during the `load` and 2) how many records will be considered during the `run`.

The `operationcount` property is how many operations will be performed during the `run`. 

All of the proportion properties effect how many of each type of operation is performed during the `run`. So, for your example read/update of 0.95/0.05, if you have a `operationcount=100` then you will have approximately 95 read operations and 5 update operations. I say approximate because the proportions are not exact they are just odds.

You can read more about the properties in the wiki: https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties.

**Comment by wuxiaomin98** [comment]
Thank you so much! @kruthar 
That makes much more sense. I do appreciate it!
