### ISSUE TITLE
Loading workloads

### ISSUE THREAD

**Issue by hassanIsBack** [brianfrankcooper/YCSB#808]
Right now we are working with one project which requires to benchmark nosql databases using a tool. We are quite new to YCSB. We found that some workloads are included in the package. We just want load those workloads into Cassandra and Riak databases and check the performance. There are some questions arises, we appreciate any help from any experts.
1. Do we need to create any database records to benchmark or we simply load those workloads to the included databases to get the results?
2. How many records are there in all the workloads? We haven't found any information that says the number of records in those workloads.
Our aim is to benchmark the performance of Cassandra and Riak and see the differences between performance for different input (record) size. Is that possible by loading those workloads? More clearly, is it possible to specify the number of records while loading an workload?
Thanks

**Comment by busbey** [comment]
> 1. Do we need to create any database records to benchmark or we simply load those workloads to the included databases to get the results?

Usually you have to do some datastore specific set up like creating a database or table. You generally do not need to do any manual record insertion. YCSB generally works through a _load_ phase followed by a _run_ phase.

There's more detail [on our wiki page for the Core Workloads](https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads#running-the-workloads), including a suggested ordering of load + run stages to go through all the workloads. If it helps, I have an [old script published on gist.github that runs through all of the core workloads](https://gist.github.com/busbey/c26ad8856d4a9434665b). It has some sharp edges, like only being tested on HBase and Accumulo. It also defaults to time-bounded runs, which means you'll almost always be testing both success and failure paths in the _run_ phase since it claims there are more possible records than actually got inserted in the ~hour or whatever time limit.

> 2. How many records are there in all the workloads? We haven't found any information that says the number of records in those workloads.

The Core Workloads come with a default record count of 1000 (ref [Workload A as an example](https://github.com/brianfrankcooper/YCSB/blob/0.10.0/workloads/workloada#L25)). Note that this is just for the _load_ phase. Some of the _run_ phases also do inserts. Also note that usually you'd tune this since most systems will insert 1k records trivially.

> Our aim is to benchmark the performance of Cassandra and Riak and see the differences between performance for different input (record) size. Is that possible by loading those workloads? More clearly, is it possible to specify the number of records while loading an workload?

Yes, you can see the aforementioned script for an example of giving a command line arg to change the number of records loaded and the number of operations performed. You should also take a look at [the docs on the properties for the Core Workloads](https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties#core-workload-package-properties) for information on changing the number of fields in a record and the size of fields.

**Comment by busbey** [comment]
Any other questions?

**Comment by gunnerVivek** [comment]
@busbey @risdenk 
I wanted to load test hbase through YCSB. But we have a requirement to test performance of HBase after specifying region splits manually. Thus we need to be able to create a user defined pattern for the row_keys, as suggested in the standard HBase guide where they prefix every row_key with `user` followed by a  number. We want to do something similar, so my question is can we ask YCSB to insert data that follows a certain pattern during load phase? Or will it only insert random data?
