### ISSUE TITLE
Question about distribution

### ISSUE THREAD

**Issue by HJVeronica** [brianfrankcooper/YCSB#819]
Hi,
I have a question about distribution.
I'm trying to benchmark Redis using YCSB.
I want to load about 20 million records, but it's too slow and the keeps being killed somehow.
so I loaded data using jedis separately and want to run it on YCSB.

But, I want to use distribution options of workloads in YCSB.
So my question is,
"Does the distribution option of YCSB matter when it load?"
I mean, even though i didnt load data in Redis using YCSB workloads, does the distribution of the YCSB workloads affect?

Sorry for bad explanation. English isn't my first language..
If you didn't understand my question, please ask me about it on the comment.
I really really need the answer.

**Comment by kruthar** [comment]
@HJVeronica - I don't think the distribution settings should matter with the insertions that happen during the `load` stage. The `load` stage, in a nutshell, counts up sequential user ids and inserts them with the proper fields. Some settings that do matter for the `load` stage are things like recordcount, fieldcount, fieldlength, dataintegrity, and insertorder. You want to make sure that what you have inserted using jedis lines up with these settings in your YCSB workload.

It is also very important that you understand how the key/id for the records is being generated with YCSB, it is critical that you mimic those keys exactly so that YCSB can operate on those keys.

The distribution settings are really for the `run` part of the workloads in which YCSB can use different distribution algorithms to choose the next key it will operate on.

**Comment by risdenk** [comment]
@HJVeronica did @kruthar's answer help?

**Comment by risdenk** [comment]
Closing as stale.
