### ISSUE TITLE
Compatibility ycsb x cassandra

### ISSUE THREAD

**Issue by cgara** [brianfrankcooper/YCSB#945]
Hi,

For version 0.12.0 of ycsb. What is the last compatible version of cassandra?
Version 3.0 of the cassandra does not have cassandra-cli.

Thank you

**Comment by jixuan1989** [comment]
Though the CQL3 in Cassandra 2.x and 3.x has more rich syntax than Cassandra 1.2,  currently the implementation of Cassandra-Client in YCSB does not care about the new feature.

Though I have not try it,  it can be compatible from Cassandra 1.2+ to 3.x, I think. It is because that the project depends on Datastax Java driver 3.0.0 (see the pom.xml).
The official document says the Java driver version supports Cassandra 1.2+ [http://docs.datastax.com/en/developer/java-driver/3.0/](http://docs.datastax.com/en/developer/java-driver/3.0/) and [https://github.com/datastax/java-driver](https://github.com/datastax/java-driver) .

By the way, Cassandra 3.x use cqlsh rather than cassandra-cli, But if you enable the thrift server, you can still use thrift API (cassandra-cli uses the same API) to connect the Cassandra server. However, only a few operations it supports now.

**Comment by gothikz** [comment]
Hello, 

I tried to load data in  Cassandra 3.11 today and it worked. I used the following command:

bin\ycsb load cassandra-cql -p hosts=localhost -P workloads\workloada -s > output.dat

Maybe that will help

**Comment by busbey** [comment]
closing as stale
